### ISSUE TITLE
How to truncate a file?

### ISSUE THREAD

**Issue by yiminglei** [pellepl/spiffs#107]
How to truncate a file?

For example,I have a 100 bytes file.After it be used.It turn to 60 bytes.But,this file size is still 100 bytes. How to truncate a file?

Thank you.

**Comment by pellepl** [comment]
In spiffs_nucleus.c, there is a `spiffs_object_truncate` function. This is an internal function, but it will do what you want. 

To call it, you need to expose it in spiffs.h - by adding e.g. `SPIFFS_truncate(spiffs *fs, const char *path, int newsize)`. Implement this new function in spiffs_hydrogen.c. You can regard functions `SPIFFS_remove` as a template for your new `SPIFFS_truncate`.

Do note, that `spiffs_object_truncate` only can make the file smaller. In posix, trunc can make files bigger. Which may seem a bit odd, but there you are.

Cheers / P

**Comment by pellepl** [comment]
feel free to reopen if necessary

**Comment by VikOlliver** [comment]
Yeah, I'd find this handy in a real world implementation...
