### ISSUE TITLE
putc and getc support

### ISSUE THREAD

**Issue by SaimenSays** [pellepl/spiffs#110]
As title describes, are there any `putc()` `getc()` functions in spiffs? Using the read/write functions with length 1 seems to be much overhead.

Thanks you all for spiffs!

**Comment by pellepl** [comment]
Sorry, there aren't. If I'd implement `putc` and `getc` I'd do it as read/writes with all the overhead (at least if I would do it) :) Guess it could be optimized somewhat, but that would probably sacrifice some safety checks. Also, regarding cache and what not, it might be more complicated than one would think at first.

**Comment by pellepl** [comment]
feel free to reopen if necessary
