### ISSUE TITLE
Confusing paragraph in Configure Spiffs wiki

### ISSUE THREAD

**Issue by kisielk** [pellepl/spiffs#113]
In the wiki for configuration:

"Now, you need to define the spiffs logical page size. The logical page size must be an integer multiple of the logical block size. You probably want several pages (>16) per block in order to utilize the flash efficiently. A logical page is the smallest data holder element in spiffs."

This doesn't really make sense to me. How can the logical page size be an integer multiple of the logical block size? You would not be able to have more pages than blocks if that were the case.

**Comment by pellepl** [comment]
Oops. It should say _The logical **block** size must be an integer multiple of the logical **page** size._

Thanks for the headsup.
