### ISSUE TITLE
Any chance this could be used with Arduino API ?

### ISSUE THREAD

**Issue by maichaell** [pellepl/spiffs#117]
Hi Pelle,

This really is not an issue but more like a question..

I'm using STM32duino framework with STM32F103C8 and 32MB Windbond flash. How much effort it would be to have this library working with Arduino SPI API ?

Thanks

**Comment by pellepl** [comment]
Hi,
Well - I have zero experience from the arduino, but given the big community I'd be surprised if there isn't a spi driver for the winbond (or some other compatible) somewhere on the net. All you need when it comes to spi flash functions are read, write and erase.
Regarding the effort it should be easier than to integrate it on e.g. an esp8266 or pic32, as the target platform for spiffs was the stm32 in the first place.

**Comment by maichaell** [comment]
I found one sketch with these methods. I tried this and it seems to work okay. 

I also just found the 'Integrate spiffs' page and it seems I do need to implement three functions.

`
    s32_t (*spiffs_read)(u32_t addr, u32_t size, u8_t *dst)
    s32_t (*spiffs_write)(u32_t addr, u32_t size, u8_t *src)
    s32_t (*spiffs_erase)(u32_t addr, u32_t size)


Could you say are these following okay ? I'm not sure about the erase method because does your interface expect to erase one byte or sector ? 

Thanks !!


`


`uint16_t read(uint32_t addr,uint8_t *buf,uint16_t n){ 
  select();
  SPI.transfer(CMD_READ_DATA);
  SPI.transfer(addr>>16);          // A23-A16
  SPI.transfer((addr>>8) & 0xFF);  // A15-A08
  SPI.transfer(addr & 0xFF);       // A07-A00
 
  uint16_t i;
  for(i = 0; i<n; i++ ) {
    buf[i] = SPI.transfer(0x00);
  }
  
  deselect();
  return i;
}`

`uint16_t fastread(uint32_t addr,uint8_t *buf,uint16_t n) {
  select();
  SPI.transfer(CMD_FAST_READ);
  SPI.transfer(addr>>16);          // A23-A16
  SPI.transfer((addr>>8) & 0xFF);  // A15-A08
  SPI.transfer(addr & 0xFF);       // A07-A00
  SPI.transfer(0x00);              // dummy
  
  uint16_t i;
  for(i = 0; i<n; i++) {
    buf[i] = SPI.transfer(0x00);
  }
  
  deselect();  
  return i;
}
`


`//
// Erase sector units (erases the data in 4kb space units)
// sect_no (in) sector number (0 - 2048)
// flgwait(in) true:waits to be processed false:No wait
// Return value: true:Successful completion false:Failure
//  Note: in the data sheet is described as normally takes 30ms, 400ms maximum erasure
//         Significant 11 bits of the address 23-bit corresponds sector number. Lower 12 bits is the sector in the address.
//
boolean eraseSector(uint16_t sect_no, boolean flgwait) {
 uint32_t addr = sect_no;
 addr<<=12;

 WriteEnable();
 select(); 
 SPI.transfer(CMD_SECTOR_ERASE);
 SPI.transfer((addr>>16) & 0xff);
 SPI.transfer((addr>>8) & 0xff);
 SPI.transfer(addr & 0xff);
 deselect();
 
 // 処理待ち
 while(IsBusy() & flgwait) {
    delay(10);
 }
 
 return true;
}
`


`
// Writing of data
// Sect_no (in): sector number (0x00 - 0x7FF)
// Inaddr (in): sector in the address (0x00-0xFFF)
// Data (in): write data storage address
// N (in): the number of bytes written (0-256)
//
uint16_t page_write(uint16_t sect_no, uint16_t inaddr, byte* data, byte n) {

  uint32_t addr = sect_no;
  int i;
  addr<<=12;
  addr += inaddr;

  WriteEnable();  
  
  if (IsBusy()) {
    return 0;  
  }

  select();
  SPI.transfer(CMD_PAGE_PROGRAM);
  SPI.transfer((addr>>16) & 0xff);
  SPI.transfer((addr>>8) & 0xff);
  SPI.transfer(addr & 0xff);

  for (i=0; i < n; i++) {
    SPI.transfer(data[i]);
  }  
  deselect();
  while(IsBusy()) ;
  
  return i;
}`

Taken from this .ino example:

`// winbond W25Q64xxx test code, 
// original library: http://tinyurl.com/ptm98pw
// by WarMonkey (luoshumymail@gmail.com)
// stripped down for STM32-Arduino and translated from Japanese by Matthias Diro (29.03.2015)
// Pin 7 (HOLD) must be set HIGH (3.3V)
// ******** from Datasheet **********
/*
The W25Q64FV array is organized into 32,768 programmable pages of 256-bytes each. 
Up to 256 bytes can be programmed at a time. Pages can be erased in groups of 16 
(4KB sector erase), groups of 128 (32KB block erase), groups of 256 (64KB block erase) 
or the entire chip (chip erase). The W25Q64FV has 2,048 erasable sectors and 128 
erasable blocks respectively. The small 4KB sectors allow for greater flexibility 
in applications that require data and parameter storage.
*/

// rough translation (original: Japanese)
// SPI serial flash memory W25Q64 operation verification program
// W25Q64 memory area structure of
// Total number of bytes 8388608
// Memory space 24-bit addressing 0x00000 - 0x7FFFFF
// Block number 128 (64KB / block)
// Sector number 2048 (4KB / sector)
// Total number of sector 2048

#include <SPI.h>
//#include <string.h>
//#define ledpin 33
#define SPI_SLAVE_SEL_PIN    7     // chip select pin number
#define MAX_BLOCKSIZE        128    // total number of blocks
#define MAX_SECTORSIZE       2048   // total number of sectors

#define CMD_WRIRE_ENABLE      0x06
#define CMD_WRITE_DISABLE     0x04
#define CMD_READ_STATUS_R1    0x05
#define CMD_READ_STATUS_R2    0x35
#define CMD_WRITE_STATUS_R    0x01 // not implemented
#define CMD_PAGE_PROGRAM      0x02
#define CMD_QUAD_PAGE_PROGRAM 0x32 // not implemented
#define CMD_BLOCK_ERASE64KB   0xd8
#define CMD_BLOCK_ERASE32KB   0x52
#define CMD_SECTOR_ERASE      0x20
#define CMD_CHIP_ERASE        0xC7 // not implemented
#define CMD_ERASE_SUPPEND     0x75 // not implemented
#define CMD_ERASE_RESUME      0x7A // not implemented
#define CMD_POWER_DOWN        0xB9
#define CMD_HIGH_PERFORM_MODE 0xA3 // not implemented
#define CMD_CNT_READ_MODE_RST 0xFF // not implemented
#define CMD_RELEASE_PDOWN_ID  0xAB // not implemented
#define CMD_MANUFACURER_ID    0x90
#define CMD_READ_UNIQUE_ID    0x4B
#define CMD_JEDEC_ID          0x9f

#define CMD_READ_DATA         0x03
#define CMD_FAST_READ         0x0B
#define CMD_READ_DUAL_OUTPUT  0x3B // not implemented
#define CMD_READ_DUAL_IO      0xBB // not implemented
#define CMD_READ_QUAD_OUTPUT  0x6B // not implemented
#define CMD_READ_QUAD_IO      0xEB // not implemented
#define CMD_WORD_READ         0xE3 // not implemented

#define SR1_BUSY_MASK	0x01
#define SR1_WEN_MASK	0x02

void setup() {
    byte buf[256];        // get data
    byte wdata[256];       // write data
    
    uint16_t n;           // number of acquired data
        Serial.begin(9600);
        delay(2000);
        Serial.println("Test in 2 seconds");
        delay(2000);
        Serial.println("Test starts");
    W25Q64_begin();        // Flash memory utilization start

    
    // Acquisition test of // JEDEC ID
    readManufacturer(buf);
    Serial.print("JEDEC ID : ");
    for (byte i=0; i< 3; i++) {
      Serial.print(buf[i],HEX);
      Serial.print(" ");
    }
    Serial.println("");
    
    // Acquisition test of Unique ID
    readUniqieID(buf);
    Serial.print("Unique ID : ");
    for (byte i=0; i< 7; i++) {
      Serial.print(buf[i],HEX);
      Serial.print(" ");
    }
    Serial.println("");
    
    // Reading of data (from address 0 to 256 bytes acquisition)
    memset(buf,0,256);
    n =  read(0,buf, 256);
    Serial.print("Read Data: n=");
    Serial.println(n,DEC);
    dump(buf,256);

    // Read of the high-speed data (from address 0 to 256 bytes acquisition)
    memset(buf,0,256);
    n =  fastread(0,buf, 256);
    Serial.print("Fast Read Data: n=");
    Serial.println(n,DEC);
    dump(buf,256);

    // Delete the sector unit
    n = eraseSector(0,true);
    Serial.print("Erase Sector(0): n=");
    Serial.println(n,DEC);
    memset(buf,0,256);
    n =  read (0,buf, 256);
    dump(buf,256);
 
    // Data writing test
    for (byte y=0; y < 255;y++) {
    for (byte i=0; i < 255;i++) {
      wdata[i]= y;
    }  
    n =  page_write(y, 0, wdata, 255);
    Serial.print("page_write(0,0,d,16): n=");
    Serial.println(n,DEC);
    memset(buf,y,256);
    n =  read (y,buf, 256);
    dump(buf,256);
    }
    // Acquisition of status register 1
    buf[0] = readStatusReg1();
    Serial.print("Status Register-1: ");
    Serial.print(buf[0],BIN);
    Serial.println("");

    // Acquisition of status register 2
    buf[0] = readStatusReg2();
    Serial.print("Status Register-2: ");
    Serial.print(buf[0],BIN);
    Serial.println("");
}

//
// Use the start of the flash memory W25Q64
// 
void W25Q64_begin() {
    pinMode (SPI_SLAVE_SEL_PIN, OUTPUT);
    SPI.begin();
    SPI.setClockDivider(SPI_CLOCK_DIV2);
   SPI.setBitOrder(MSBFIRST);
  SPI.setDataMode(SPI_MODE0);
    deselect();
}

//
// Use the end of the flash memory W25Q64
// 
void W25Q64_end() {
  powerDown();
   SPI.end();
}

//
// Chip select
// I want to select a flash memory operation
//
void select() {
   digitalWrite(SPI_SLAVE_SEL_PIN, LOW); 
}

//
// Chip deselected
// I make a flash memory operation to Yuhi selection
//
void deselect() {
   digitalWrite(SPI_SLAVE_SEL_PIN, HIGH); 
}

//
// Values obtained in the status register 1
// Returns: status register value of 1
//
byte readStatusReg1() {
  byte rc;
  select();
  SPI.transfer(CMD_READ_STATUS_R1);
  rc = SPI.transfer(0xFF);
  deselect();
  return rc;
}

//
//Values obtained in the status register 2
//  Returns: status register 2 of value
//
byte readStatusReg2() {
  byte rc;
  select();
  SPI.transfer(CMD_READ_STATUS_R2);
  rc = SPI.transfer(0xFF);
  deselect();
  return rc;
}

//
// Acquisition of JEDEC ID(Manufacture, Memory Type,Capacity)
// d (out): Manufacture, Memory Type, store the 3 bytes of Capacity
//
void readManufacturer(byte* d) {
  select();
  SPI.transfer(CMD_JEDEC_ID);
  for (byte i =0; i <3; i++) {
    d[i] = SPI.transfer(0x00);
  } 
  deselect();
}

//
// Acquisition of Unique ID
// d (out):  returns the Unique ID 7 bytes
//
void readUniqieID(byte* d) {
  select();
  SPI.transfer(CMD_READ_UNIQUE_ID);
  SPI.transfer(0x00);
  SPI.transfer(0x00);
  SPI.transfer(0x00);
  SPI.transfer(0x00);
  for (byte i =0; i <7; i++) {
    d[i] = SPI.transfer(0x00);
  }
 deselect(); 
}

//
// During the processing of writing such as check
// Return Value: true: work, false: in idle
//
boolean IsBusy() {
  uint8_t r1;
  select();
  SPI.transfer(CMD_READ_STATUS_R1);
  r1 = SPI.transfer(0xff);
  deselect();
  if(r1 & SR1_BUSY_MASK)
    return true;
  return false;
}

//
//　Power down the specified 
//
void powerDown() {
  select();
  SPI.transfer(CMD_POWER_DOWN);
  deselect();
}

//
// Write permission settings
//
void WriteEnable() {
  select();
  SPI.transfer(CMD_WRIRE_ENABLE);
  deselect();
}

//
// Write-protect setting
//
void WriteDisable() {
  select();
  SPI.transfer(CMD_WRITE_DISABLE);
  deselect();
}

//
// Reading data
// addr (in): read start address (24 bits 0x00000 - 0xFFFFF)
// n (in): the number of read data
//
uint16_t read(uint32_t addr,uint8_t *buf,uint16_t n){ 
  select();
  SPI.transfer(CMD_READ_DATA);
  SPI.transfer(addr>>16);          // A23-A16
  SPI.transfer((addr>>8) & 0xFF);  // A15-A08
  SPI.transfer(addr & 0xFF);       // A07-A00
 
  uint16_t i;
  for(i = 0; i<n; i++ ) {
    buf[i] = SPI.transfer(0x00);
  }
  
  deselect();
  return i;
}

//
// Read of the high-speed data
// addr (in): read start address (24 bits 0x00000 - 0xFFFFF)
// n (in): the number of read data
//
uint16_t fastread(uint32_t addr,uint8_t *buf,uint16_t n) {
  select();
  SPI.transfer(CMD_FAST_READ);
  SPI.transfer(addr>>16);          // A23-A16
  SPI.transfer((addr>>8) & 0xFF);  // A15-A08
  SPI.transfer(addr & 0xFF);       // A07-A00
  SPI.transfer(0x00);              // dummy
  
  uint16_t i;
  for(i = 0; i<n; i++) {
    buf[i] = SPI.transfer(0x00);
  }
  
  deselect();  
  return i;
}

//
// Erase sector units (erases the data in 4kb space units)
// sect_no (in) sector number (0 - 2048)
// flgwait(in) true:waits to be processed false:No wait
// Return value: true:Successful completion false:Failure
//  Note: in the data sheet is described as normally takes 30ms, 400ms maximum erasure
//         Significant 11 bits of the address 23-bit corresponds sector number. Lower 12 bits is the sector in the address.
//
boolean eraseSector(uint16_t sect_no, boolean flgwait) {
 uint32_t addr = sect_no;
 addr<<=12;

 WriteEnable();
 select(); 
 SPI.transfer(CMD_SECTOR_ERASE);
 SPI.transfer((addr>>16) & 0xff);
 SPI.transfer((addr>>8) & 0xff);
 SPI.transfer(addr & 0xff);
 deselect();
 
 // 処理待ち
 while(IsBusy() & flgwait) {
    delay(10);
 }
 
 return true;
}

//
// 64KB block erase (erasing the data in the 64kb space units)
// blk_no (in) block number (0 - 127)
// flgwait(in) true:waiting to be processed false: no wait
// Return value: true:Successful completion false:Failure
//   Note: in the data sheet is described as normally takes 150ms, 1000ms maximum erasure
//         Upper 7 bits of the address 23-bit is equivalent of block. Lower 16 bits will be block address.
//
boolean erase64Block(uint16_t blk_no, boolean flgwait) {
 uint32_t addr = blk_no;
 addr<<=16;

 WriteEnable();
 select(); 
 SPI.transfer(CMD_BLOCK_ERASE64KB);
 SPI.transfer((addr>>16) & 0xff);
 SPI.transfer((addr>>8) & 0xff);
 SPI.transfer(addr & 0xff);
 deselect();
 
 // 処理待ち
 while(IsBusy() & flgwait) {
    delay(50);
 }
 
 return true;
}


//
// (erasing the data in the 32kb space units) 32KB block erase
// Blk_no (in) block number (0 - 255)
// Flgwait (in) true: false perform a process waiting: waiting None
// Return value: true: successful completion false: failure
// Note: in the data sheet it has been described as usually takes 120ms, 800ms maximum to erase
// Upper 8 bits of the address 23-bit corresponds to block. Lower 15 bits is the block address.
boolean erase32Block(uint16_t blk_no, boolean flgwait) {

 uint32_t addr = blk_no;
 addr<<=15;

 WriteEnable();  
 select(); 
 SPI.transfer(CMD_BLOCK_ERASE32KB);
 SPI.transfer((addr>>16) & 0xff);
 SPI.transfer((addr>>8) & 0xff);
 SPI.transfer(addr & 0xff);
 deselect();
 
 // Waiting to be processed
 while(IsBusy() & flgwait) {
    delay(50);
 }
 
 return true;
}

//
// 全領域の消去
// flgwait(in) true:処理待ちを行う false:待ち無し
// 戻り値: true:正常終了 false:失敗
//   補足: データシートでは消去に通常 15s 、最大30sかかると記載されている

// Erase of the entire region
// Flgwait (in) true: false perform a process waiting: waiting None
// Return value: true: successful completion false: failure
// Note: in the data sheets are described as normally takes 15s, 30s up to the clear
//
boolean eraseAll(boolean flgwait) {
 WriteEnable();  
 select(); 
 SPI.transfer(CMD_CHIP_ERASE);
 deselect();

 // Waiting to be processed
 while(IsBusy() & flgwait) {
    delay(500);
 }
 
 deselect();
 return true;
}

//
// Writing of data
// Sect_no (in): sector number (0x00 - 0x7FF)
// Inaddr (in): sector in the address (0x00-0xFFF)
// Data (in): write data storage address
// N (in): the number of bytes written (0-256)
//
uint16_t page_write(uint16_t sect_no, uint16_t inaddr, byte* data, byte n) {

  uint32_t addr = sect_no;
  int i;
  addr<<=12;
  addr += inaddr;

  WriteEnable();  
  
  if (IsBusy()) {
    return 0;  
  }

  select();
  SPI.transfer(CMD_PAGE_PROGRAM);
  SPI.transfer((addr>>16) & 0xff);
  SPI.transfer((addr>>8) & 0xff);
  SPI.transfer(addr & 0xff);

  for (i=0; i < n; i++) {
    SPI.transfer(data[i]);
  }  
  deselect();
  while(IsBusy()) ;
  
  return i;
}

//
// Dump list of write data
// Dt (in): data storage start address
// N (in): the number of display data
void dump(byte *dt, int n) {
  unsigned long sz;
  char buf[64];
  int clm = 0;
  byte data;
  byte sum;
  byte vsum[16];
  byte total =0;
  int saddr =0;
  int eaddr =n-1;
  sz = eaddr -saddr;
  
  Serial.println("----------------------------------------------------------");
  
  for (int i=0;i<16;i++) vsum[i]=0;  
  for (unsigned long addr = saddr; addr <= eaddr; addr++) {
    data = dt[addr];
    if (clm == 0) {
      sum =0;
      sprintf(buf,"%05lx: ",addr);
      Serial.print(buf);
    }

    sum+=data;
    vsum[addr % 16]+=data;
    
    sprintf(buf,"%02x ",data);
    Serial.print(buf);
    clm++;
    if (clm == 16) {
      sprintf(buf,"|%02x ",sum);
      Serial.print(buf);      
      Serial.println("");
      clm = 0;
    }    
  }
  Serial.println("----------------------------------------------------------");
  Serial.print("       ");
  for (int i=0; i<16;i++) {
    total+=vsum[i];
    sprintf(buf,"%02x ",vsum[i]);
    Serial.print(buf);
  }
  sprintf(buf,"|%02x ",total);
  Serial.print(buf);      
  Serial.println("");
  Serial.println("");
}

void loop() {

}`

**Comment by pellepl** [comment]
By a quick glance it looks OK.  The erase hal function expects sector erase, spi flashes cannot be erased byte wise. The length will always be SPIFFS_PHYS_ERASE_SIZE. I recommend looking through the wiki thoroughly 😉

**Comment by maichaell** [comment]
Thanks! Wiki is really good - I'll study that.

**Comment by maichaell** [comment]
Just tried to integrate this. Run into this:

`
Compiling .pioenvs\bluepill_f103c8\src\spiffs-master\src\spiffs_cache.o
Compiling .pioenvs\bluepill_f103c8\src\spiffs-master\src\spiffs_check.o
Compiling .pioenvs\bluepill_f103c8\src\spiffs-master\src\spiffs_gc.o
spiffs-master\src\spiffs_gc.c: In function 'spiffs_gc_find_candidate':
spiffs-master\src\spiffs_gc.c:258:28: error: 'intptr_t' undeclared (first use in this function)
cand_scores = (s32_t*)(((intptr_t)cand_scores + sizeof(intptr_t) - 1) & ~(sizeof(intptr_t) - 1));
^
spiffs-master\src\spiffs_gc.c:258:28: note: each undeclared identifier is reported only once for each function it appears in
spiffs-master\src\spiffs_gc.c:258:37: error: expected ')' before 'cand_scores'
cand_scores = (s32_t*)(((intptr_t)cand_scores + sizeof(intptr_t) - 1) & ~(sizeof(intptr_t) - 1));
^
Compiling .pioenvs\bluepill_f103c8\src\spiffs-master\src\spiffs_hydrogen.o
*** [.pioenvs\bluepill_f103c8\src\spiffs-master\src\spiffs_gc.o] Error 1
spiffs-master\src\spiffs_hydrogen.c: In function 'SPIFFS_mount':
spiffs-master\src\spiffs_hydrogen.c:94:27: error: 'intptr_t' undeclared (first use in this function)
u8_t addr_lsb = ((u8_t)(intptr_t)fd_space) & (ptr_size-1);
^
spiffs-master\src\spiffs_hydrogen.c:94:27: note: each undeclared identifier is reported only once for each function it appears in
spiffs-master\src\spiffs_hydrogen.c:94:36: error: expected ')' before 'fd_space'
u8_t addr_lsb = ((u8_t)(intptr_t)fd_space) & (ptr_size-1);
^
spiffs-master\src\spiffs_hydrogen.c:103:31: error: expected ')' before 'cache'
addr_lsb = ((u8_t)(intptr_t)cache) & (ptr_size-1);
^
*** [.pioenvs\bluepill_f103c8\src\spiffs-master\src\spiffs_hydrogen.o] Error 1
 [ERROR] Took 1.17 seconds 
Process terminated with status 1 (0 minute(s), 1 second(s))
5 error(s), 0 warning(s) (0 minute(s), 1 second(s))
 
`

**Comment by pellepl** [comment]
See this - http://www.cplusplus.com/reference/cstdint/. Seems you need to include stdint.h, or simply typedef intptr_t to s32_t in spiffs_config.h, given your target is using 32 bit addressing.

**Comment by maichaell** [comment]
Getting there... mount return 0 but writing a file: -10010. I seem to have a problem in write function it does not write bytes but the whole buffer. The function is not my creation. I need to fix that. 

```
void winbondFlashClass::writePage(uint32_t addr_start,uint8_t *buf)
{
    char buff[64];
    sprintf(buff,">writePage: addr:%d\n",addr_start);
    Serial.println(buff);

  select();
  transfer(PAGE_PGM);
  transfer(addr_start>>16);
  transfer(addr_start>>8);
  transfer(0x00);
  uint8_t i=0;
  do {
    transfer(buf[i]);
    Serial.print((char)buf[i]);
    i++;
  }while(i!=0);
  deselect();

}
````

**Comment by maichaell** [comment]
One question, does the write function send address in bytes or in page number?

``` 
my_spiffs_write(u32_t addr, u32_t size, u8_t *src) {
...
}
```

**Comment by pellepl** [comment]
In bytes. The actual, physical address of  the spiflash.

**Comment by maichaell** [comment]
Ok, Thanks for the info!

Sorry if this is basic info but I've never used SPI Flash chips before. So just to confirm that my write operations are correct..  

Does this 'Page Program' operation (WinBond 32Mbit) expect to have  the page number as a parameter or actual physical bytes in flash ? 


_**8.2.15 Page Program (02h)**
The Page Program instruction allows from one byte to 256 bytes (a page) of data to be programmed at
previously erased (FFh) memory locations. A Write Enable instruction must be executed before the device
will accept the Page Program Instruction (Status Register bit WEL= 1). The instruction is initiated by
driving the /CS pin low then shifting the instruction code “02h” followed by a **24-bit address (A23-A0)** and
at least one data byte, into the DI pin. The /CS pin must be held low for the entire length of the instruction
while data is being sent to the device. The Page Program instruction sequence is shown in Figure 29._

**Comment by pellepl** [comment]
Heh, no problem, it can be confusing. It's address, not page index for the spiflash itself also. Do mind though, page boundaries cannot be crossed. Say your flash has 256 byte pages, and you want to write 512 bytes to address 8 and onwards. Then you have to issue a write command for each page, that is one write command for bytes 8-255, one for bytes 256-511, and one for bytes 512-520.

**Comment by pellepl** [comment]
Forgot to mention that if spiffs is configured with a logical page size
being same or less as the actual page size of the spiflash, you do not have
to worry about page crossings in your driver. spiffs will handle that for
you. On the other hand it is of course nice having a spiflash driver coping
with general cases also.

Den 7 dec. 2016 4:59 PM skrev "Peter Andersson" <notifications@github.com>:

**Comment by maichaell** [comment]
Ok, thanks for the info!

Well I'm still having hard time to get it working. Basically I've used info from 'integrate' section in the wiki. And I'm using test file that creates file with 'hello world'. I have winbond 32Mbit chip

I've checked that write/read/erase spi functions work as supposed on my stm32.

In the program I do chip erase first. Then mounting fs (returns 0) and then running the test program. Write returns -10010.

I'm a bit out of ideas. What should I try next?

one question abut write. Even spiffs instructs to write 45 bytes should the code really write only 45 bytes? I've understood that it doesn't matter because whole page is written always in one operation and 'by design'.

**Comment by pellepl** [comment]
Perhaps that is the problem - the file system very often (if not always)
writes only parts of pages. If you get a call to write 4 bytes of data to
0x123456, you must only write those four bytes.

**Comment by maichaell** [comment]
Hey, got it working !! Seems to work okay! Thanks for all the help.

I got two problems:

- did not check for 'busy' status from flash before write/read/erase operations
- wrote always 256 bytes to the flash even spiffs requested less..

Here's some debug bytes for you ;-) it first mounts and then executes the test program

```spiffs_read: addr:254, size:2
spiffs_read: addr:33022, size:2
spiffs_read: addr:65790, size:2
spiffs_read: addr:98558, size:2
spiffs_read: addr:131326, size:2
spiffs_read: addr:164094, size:2
spiffs_read: addr:196862, size:2
spiffs_read: addr:229630, size:2
spiffs_read: addr:262398, size:2
spiffs_read: addr:295166, size:2
spiffs_read: addr:327934, size:2
spiffs_read: addr:360702, size:2
spiffs_read: addr:393470, size:2
spiffs_read: addr:426238, size:2
spiffs_read: addr:459006, size:2
spiffs_read: addr:491774, size:2
spiffs_read: addr:0, size:256
spiffs_read: addr:32768, size:256
spiffs_read: addr:65536, size:256
spiffs_read: addr:98304, size:256
spiffs_read: addr:131072, size:256
spiffs_read: addr:163840, size:256
spiffs_read: addr:196608, size:256
spiffs_read: addr:229376, size:256
spiffs_read: addr:262144, size:256
spiffs_read: addr:294912, size:256
spiffs_read: addr:327680, size:256
spiffs_read: addr:360448, size:256
spiffs_read: addr:393216, size:256
spiffs_read: addr:425984, size:256
spiffs_read: addr:458752, size:256
spiffs_read: addr:491520, size:256
mount res:0
TEST SPIFFS spiffs_read: addr:0, size:256
spiffs_read: addr:32768, size:256
spiffs_read: addr:65536, size:256
spiffs_read: addr:98304, size:256
spiffs_read: addr:131072, size:256
spiffs_read: addr:163840, size:256
spiffs_read: addr:196608, size:256
spiffs_read: addr:229376, size:256
spiffs_read: addr:262144, size:256
spiffs_read: addr:294912, size:256
spiffs_read: addr:327680, size:256
spiffs_read: addr:360448, size:256
spiffs_read: addr:393216, size:256
spiffs_read: addr:425984, size:256
spiffs_read: addr:458752, size:256
spiffs_read: addr:491520, size:256
spiffs_read: addr:0, size:256
spiffs_read: addr:32768, size:256
spiffs_read: addr:65536, size:256
spiffs_read: addr:98304, size:256
spiffs_read: addr:131072, size:256
spiffs_read: addr:163840, size:256
spiffs_read: addr:196608, size:256
spiffs_read: addr:229376, size:256
spiffs_read: addr:262144, size:256
spiffs_read: addr:294912, size:256
spiffs_read: addr:327680, size:256
spiffs_read: addr:360448, size:256
spiffs_read: addr:393216, size:256
spiffs_read: addr:425984, size:256
spiffs_read: addr:458752, size:256
spiffs_read: addr:491520, size:256
spiffs_read: addr:0, size:256
spiffs_write: addr:0, size:2
>writePageBytes: addr:0, bytes:2
1,80,<writepageBytes
spiffs_write: addr:256, size:45
>writePageBytes: addr:256, bytes:45
1,80,0,0,F8,0,0,0,FF,FF,FF,FF,1,6D,79,5F,66,69,6C,65,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,<writepageBytes
spiffs_read: addr:256, size:256
Write:
OK0
Close:
spiffs_write: addr:2, size:2
>writePageBytes: addr:2, bytes:2
1,0,<writepageBytes
spiffs_write: addr:512, size:5
>writePageBytes: addr:512, bytes:5
1,0,0,0,FC,<writepageBytes
spiffs_write: addr:517, size:12
>writePageBytes: addr:517, bytes:12
48,65,6C,6C,6F,20,77,6F,72,6C,64,0,<writepageBytes
spiffs_write: addr:256, size:256
>writePageBytes: addr:256, bytes:256
1,80,0,0,F8,0,0,0,C,0,0,0,1,6D,79,5F,66,69,6C,65,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,2,0,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,FF,<writepageBytes
Open:spiffs_read: addr:512, size:256
READ OK
Hello world
DONE
```

**Comment by pellepl** [comment]
Great! Good work! Do try and create and delete a lot of files also, just to make sure the erase works.

**Comment by maichaell** [comment]
Good idea!

I have:
#define SPIFFS_CFG_PHYS_ERASE_SZ(ignore)  (32*1024)

and I get a call to erase 32kB
spiffs_erase: addr:327680, size:32768

.. so will spiffs always erase by the size what's defined  SPIFFS_CFG_PHYS_ERASE_SZ(ignore) and not any smaller ?

WinBond supports 4kB,32kB and 64kB erase operations. 32kB must be faster than 4kB but if I want best write performance and I'm not concerned about wasting extra bytes of space is 32/64kB better than 4kB for erase size ?

Thanks.

**Comment by pellepl** [comment]
Yep, hal_erase will always be called with SPIFFS_CFG_PHYS_ERASE_SZ as size.

As you say, if you're not concerned about wasting bytes compared to
performance, bigger erase sizes are better than small.

2016-12-09 10:09 GMT+01:00 maichaell <notifications@github.com>:

**Comment by maichaell** [comment]
Thanks! It works just fine. 

One question about directories. I understood there's no directory structure like we usually understand in Linux or Windows but I can see there are functions for directoreis. This is okay but I want to list available files somehow.

I've created files in "empty" directory. like: 

`SPIFFS_open(&fs, "my_file", SPIFFS_CREAT | SPIFFS_APPEND| SPIFFS_RDWR, 0);`

Can I list them or should I create them in '/' 

SPIFFS_open(&fs, "/my_file", SPIFFS_CREAT | SPIFFS_APPEND| SPIFFS_RDWR, 0);

?

Then I tried this: 

`SPIFFS_opendir(&fs, "", &d); `

and it seems to fault my board.

Thanks!

**Comment by pellepl** [comment]
If you create a file named "/foo" you'll get a file with name "/foo".
Creating a file "foo" will be a new file named "foo", not related to "/foo"
in any way.
In SPIFFS_opendir, the directory argument is ignored, so it should work.
There is an example on the wiki, under Under spiffs.

Den 9 dec. 2016 11:44 AM skrev "maichaell" <notifications@github.com>:

**Comment by maichaell** [comment]
Thanks, got it!

If I use RTOS.. can you say what operations are "thread-safe" ? For example can I open/read same file from two different tasks ? I found there's possibility to define a mutex through config

```
SPIFFS_LOCK(fs)
```

Should I implement these if using RTOS ? Thanks.

**Comment by pellepl** [comment]
When using rtos you must define mutex in SPIFFS_LOCK and SPIFFS_UNLOCK. It
is OK to open same file in different threads as long as the spiffs stack
never calls into itself. Which the mutex will prevent.


Den 9 dec. 2016 12:51 PM skrev "maichaell" <notifications@github.com>:

Thanks, got it!

If I use RTOS.. can you say what operations are "thread-safe" ? For example
can I open/read same file from two different tasks ? I found there's
possibility to define a mutex through config

SPIFFS_LOCK(fs)

Should I implement these if using RTOS ? Thanks.

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/pellepl/spiffs/issues/117#issuecomment-265996690>, or mute
the thread

**Comment by pellepl** [comment]
feel free to reopen if necessary
