### ISSUE TITLE
Suggest to safely remove "GCC diagnostic" pragmas

### ISSUE THREAD

**Issue by yihcdaso-yeskela** [pellepl/spiffs#14]
Instead of
```C
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wpointer-to-int-cast"
    u8_t addr_lsb = ((u8_t)fd_space) & (ptr_size-1);
#pragma GCC diagnostic pop
```
you can write
```C
    u8_t addr_lsb = (u8_t)(((intptr_t)fd_space) & (ptr_size-1));
```
it assumes including `<stdint.h>` for `intptr_t` definition

**Comment by pellepl** [comment]
Yes, thought of that. However, at the time of coding this my baremetal crossgcc does not behave together with stdint.h. I totally agree that intptr_t is much more beautiful, though I'd like to keep current implementation a while further.
