### ISSUE TITLE
Different object ID

### ISSUE THREAD

**Issue by spe-ciellt** [pellepl/spiffs#141]
Hi,

When looping out existing files using opendir()/readdir()/closedir() I get object ID with most significant bit set (0x8000). When I query on a separate file using stat/fstat I get object ID with the most significant bit not set. I see in spiffs_hydrogen.c function spiffs_stat_pix you do:
`s->obj_id = obj_id & ~SPIFFS_OBJ_ID_IX_FLAG;`

Should the masking be made on obj_id reponse from readdir() too?

Or am I out biking? ;)

Thanks,
/Stefan

**Comment by rojer** [comment]
this was (or was supposed to have been) fixed in https://github.com/pellepl/spiffs/commit/bc87d0b44cd6e70147572173cd068a0b1cbc8b33

**Comment by spe-ciellt** [comment]
Oh, didn't notice, thank you! Seems like I have some patching to do.
