### ISSUE TITLE
Problem with SPIFFS_lseek after exactly 26355 bytes written

### ISSUE THREAD

**Issue by mariankr** [pellepl/spiffs#148]
Hi everyone!
I find interesting problem with `SPIFFS_lseek` which fails after exactly after 26355 bytes written to file.
There is code to reproduce:

```
TEST(seek_bug) {
  int res;
  fs_reset_specific(0, 0, 8*1024*1024, 4096, 4096, 256);
  int i = 0;
  do
  {
    spiffs_file fd = SPIFFS_open(FS, "EVENT", SPIFFS_CREAT | SPIFFS_RDWR, 0);
    if (SPIFFS_lseek(FS, fd, 0, SEEK_END) < 0)
    {
      printf("try number: %i\n", i);
      printf("seek errno %i\n", SPIFFS_errno(FS));
      SPIFFS_vis(FS);
      return SPIFFS_errno(FS);
    }
    static unsigned char buf[1] = {}; // data doesn't matter
    if (SPIFFS_write(FS, fd, &buf, sizeof(buf)) < 0) printf("errno %i\n", SPIFFS_errno(FS));
    SPIFFS_close(FS, fd);
  } while (i++ < 1000000);
  SPIFFS_vis(FS);
  return TEST_RES_OK;
} TEST_END
```
seek failed after exactly 26355 bytes written.

I look into it a little and figured that function `spiffs_obj_lu_find_entry_visitor` returns `SPIFFS_VIS_END`
and this is causing `SPIFFS_ERR_NOT_FOUND` return code from `SPIFFS_lseek`

Debug output (without cache): 
[out.zip](https://github.com/pellepl/spiffs/files/1028246/out.zip)

I checked that:
1. This is independent of cache setting
2. Writing 26355 x 1 byte has same effect that writing 1 x 26355 bytes
3. Writing 26355+1 byte is OK :-)
4. Number of writes that causing this issue depends of page size (or maybe another parameters of FS).

Maybe somebody have an idea what is reason?

All the best! Marian.

**Comment by pellepl** [comment]
thanks for the report, got it fixed.
