### ISSUE TITLE
does spiffs is C90 compilant?

### ISSUE THREAD

**Issue by iceberg1369** [pellepl/spiffs#150]
I would like to compile spiffs in RVCT 3.1 which only accepts C90 standard. so is it possible to compile it by RVCT 3.1?

**Comment by pellepl** [comment]
Hi,

not of the moment no. However, if I force gcc here to be C90 compliant, the only errors I get seem to be about me using // comments here and there so it should be easily fixed. I think there are some gcc pragmas also, which also ought to be easily translated.
