### ISSUE TITLE
FileExist inconsistence.

### ISSUE THREAD

**Issue by joseasenz** [pellepl/spiffs#154]
Hi all.

I have two spiffs instances running on separate drives.

If the drive 1 contains a file "myfile" and I check if a file with same name exists in the drive 2, it seems that the existence of the file in the first drive affects the result.

This is how I check if the file exists:

	while ((pe = SPIFFS_readdir(&d, pe)))
	{
	    if (0 == strncmp(pathPtr, (char *)pe->name, strlen(pathPtr)))
	    {
	    	fileExists = TRUE;
	    	break;
	    }
	}

Regards

**Comment by kisielk** [comment]
is SPIFFS_CACHE enabled? if so, are you passing a different cache memory to each filesystem?

**Comment by joseasenz** [comment]
Great!
That was the origin of that problem and other problems I had.

Many thanks, kisielk
