### ISSUE TITLE
Possible error in test_spiffs.c

### ISSUE THREAD

**Issue by yihcdaso-yeskela** [pellepl/spiffs#21]
test_spiffs.c:
339 void fs_reset_specific(u32_t addr_offset, u32_t phys_addr, u32_t phys_size,
340     u32_t phys_sector_size,
341     u32_t log_block_size, u32_t log_page_size) {
342   fs_set_addr_offset(addr_offset);
....
360    res = SPIFFS_mount(&__fs, &c, _work, _fds, sizeof(_fds), _cache, sizeof(_cache), spiffs_check_cb_f)

Calling `SPIFFS_mount` with parameters undefined in `fs_reset_specific` (`c` for example). Suggest there should be 

    res = fs_mount_specific(phys_addr, phys_size, phys_sector_size, log_block_size, log_page_size);

instead.

**Comment by pellepl** [comment]
So true.  Copy paste error. Thanks for spotting it.
