### ISSUE TITLE
flash mount problem

### ISSUE THREAD

**Issue by devy13** [pellepl/spiffs#220]
hello
i am using W25Q128FV flash chiop and CYC8CKit-050 cypress kit 
i tried to implement SPIFFS, but got SPIFFS_ERR_NOT_A_FS, with SPIFFS_USE_MAGIC enable
how can i solve this?
i am attaching my code here
[TFT_SSD1963.cywrk.Archive04.zip](https://github.com/pellepl/spiffs/files/2296657/TFT_SSD1963.cywrk.Archive04.zip)

**Comment by sensslen** [comment]
Have you formatted the Flash using spiffs_format before you tried to mout it?

**Comment by sensslen** [comment]
Before being able to write to the File System, be sure it is formatted. With Spiffs, you have to unmount the File System, format it using spiffs_format and then remount it. 

After this you should not encounter any problems reading and writing Files, at least if your Hardware abstraction works as expected.

**Comment by devy13** [comment]
Unmount,format and remount got -10025 error

**Comment by sensslen** [comment]
Please verify, that your Hal driver works properly.

As an alternative, I recommend to simulate spiffs with a small desktop application with a file as backend...

**Comment by devy13** [comment]
Can you see any mistake in my HAL driver,because it ia working correct if i
read write and erase without spiffs

**Comment by devy13** [comment]
hi
i solved the issue , it was in erase function of HAL driver
thanks for support
