### ISSUE TITLE
Is it possible to create contiguous file then get physical address of it with current API

### ISSUE THREAD

**Issue by omersiar** [pellepl/spiffs#227]
If this is possible, one can create a contiguous file on SPIFFS to update the running sketch by eboot bootloader's copying function on ESP8266.

EBOOT needs to know to physical start address of the file and size, this information can be fed to RTC memory and simple reboot will replace running sketch with the file on SPIFFS.

**Comment by igrr** [comment]
See https://github.com/pellepl/spiffs/issues/226, which is essentially the same request. Not possible because each page has a few bytes for metadata, so the actual file data is not contiguous.

**Comment by omersiar** [comment]
Thanks.
