### ISSUE TITLE
spiffs_object_read() read past end of file

### ISSUE THREAD

**Issue by apwise** [pellepl/spiffs#237]
In spiffs_object_read(), there's code to compute how much data can be read in each "chunk":

https://github.com/pellepl/spiffs/blob/1350deb54c097fd06133f3c6d39dd3532a229829/src/spiffs_nucleus.c#L2028-L2033

surely the last of the tests above should be:
`    len_to_read = MIN(len_to_read, (fd->size - cur_offset));`

as it should be testing how much data remains in the file to be read, not the total file size?

**Comment by pellepl** [comment]
Yeah, makes sense. I'll look it over. Good catch!

Den sön 24 mars 2019 09:17Adrian Wise <notifications@github.com> skrev:

**Comment by pellepl** [comment]
@apwise: thanks!
