### ISSUE TITLE
Zero-size file cannot be seek

### ISSUE THREAD

**Issue by lishen2** [pellepl/spiffs#57]
An empty file (zero bytes) cannot be seek to the end or beginning
The errno returned is SPIFFS_ERR_END_OF_OBJECT

Bug is in 'SPIFFS_lseek'
```
  if (offs > (s32_t)fd->size) {
    res = SPIFFS_ERR_END_OF_OBJECT;
  }
```
When seeking empty file, fd->size is SPIFFS_UNDEFINED_LEN , the statement (offs > (s32_t)fd->size) success (zero is bigger than negative number).
The following modification will work:
```
  if ((offs > (s32_t)fd->size) && (SPIFFS_UNDEFINED_LEN != fd->size)) {
    res = SPIFFS_ERR_END_OF_OBJECT;
  }
```

**Comment by pellepl** [comment]
Ah yes, you're right.  Good spottning,  thanks!

**Comment by lishen2** [comment]
I feel like I should thank you for create spiffs and maintain it.

**Comment by pellepl** [comment]
Thanks! Always fun when people find use of something home-tinkered ;) I'll fix the issue this evening.
