### ISSUE TITLE
Lots of static analysis bugs

### ISSUE THREAD

**Issue by mkschreder** [pellepl/spiffs#6]
spiffs_nucleus.c	spiffs_object_modify	line 1218 new_objix_pix is never initialized
spiffs_nucleus.c	spiffs_obj_lu_find_free_obj_id	line 1710	possible division by zero

state.compaction = (state.max_obj_id-state.min_obj_id) / ((SPIFFS_CFG_LOG_PAGE_SZ(fs) / sizeof(u8_t)));

Also lots of warnings for never read result value. Better to not store result at all otherwise written code has no effect. 

spiffs_nucleus.c	spiffs_object_modify	line 1135 value of res is never read
spiffs_hydrogen.c	SPIFFS_write	line 324 value of res never read
spiffs_hydrogen.c	SPIFFS_check line 	700 res never read
...

**Comment by pellepl** [comment]
Could you please inform me of what compiler and with what flags you encounter this?

**Comment by mkschreder** [comment]
Clang scan-build with arm-none-eabi-gcc with -Wall

**Comment by pellepl** [comment]
Ok thanks. Seems plain linux gcc -Wall does not report as much as an arm cross-compiled gcc. Weird. I'll  look into it and fix it.

**Comment by mkschreder** [comment]
For maximum effect: 

gcc:
-Wall -Wno-format-y2k -W -Wstrict-prototypes -Wmissing-prototypes \
-Wpointer-arith -Wreturn-type -Wcast-qual -Wwrite-strings -Wswitch \
-Wshadow -Wcast-align -Wchar-subscripts -Winline \
-Wnested-externs -Wredundant-decls

g++:
-Wall -Wno-format-y2k -W \
-Wpointer-arith -Wreturn-type -Wcast-qual -Wwrite-strings -Wswitch \
-Wcast-align -Wchar-subscripts -Wredundant-decls

**Comment by pellepl** [comment]
Fixed. Phew. Found one bug amongst all warnings. Thanks!
