### ISSUE TITLE
Minor tweaks

### ISSUE THREAD

**Issue by Nails-** [pellepl/spiffs#81]
For these macros:
#define SPIFFS_API_CHECK_MOUNT(fs) \
  if (!SPIFFS_CHECK_MOUNT((fs))) { \
    (fs)->err_code = SPIFFS_ERR_NOT_MOUNTED; \
    return -1; \
  }

#define SPIFFS_API_CHECK_CFG(fs) \
  if (!SPIFFS_CHECK_CFG((fs))) { \
    (fs)->err_code = SPIFFS_ERR_NOT_CONFIGURED; \
    return -1; \
  }

#define SPIFFS_API_CHECK_RES(fs, res) \
  if ((res) < SPIFFS_OK) { \
    (fs)->err_code = (res); \
    return -1; \
  }

#define SPIFFS_API_CHECK_RES_UNLOCK(fs, res) \
  if ((res) < SPIFFS_OK) { \
    (fs)->err_code = (res); \
    SPIFFS_UNLOCK(fs); \
    return -1; \
  }

Instead of returning -1, can you please change this to return the actual error codes instead of -1? The issue that might arise is that you may not get the correct error code if you have to rely upon the SPIFFS_errno function in a multi-threaded environment.  For example, when one thread encounters some error on a spiffs filesystem, but gets switched out for another thread that uses SPIFFS with the same filesystem, and it then encounters some other type of error.  When the original thread returns and reads the error_code, won't it get the second thread's error number?

I am proposing a simple change to these for functions to return these values:
SPIFFS_API_CHECK_MOUNT   --  return SPIFFS_ERR_NOT_MOUNTED;
SPIFFS_API_CHECK_CFG -- return SPIFFS_ERR_NOT_CONFIGURED;
 SPIFFS_API_CHECK_RES -- return res;
SPIFFS_API_CHECK_RES_UNLOCK -- return res;

Also my compiler issues annoying remarks (but still compiles fine) that could easily be fixed.  They are:
spiffs-master/src/spiffs.h", line 107: remark #230-D: trailing comma is nonstandard                                                               
spiffs-master/src/spiffs.h", line 126: remark #230-D: trailing comma is nonstandard                                                               
spiffs-master/src/spiffs_cache.c", line 17: remark #270-D: declaration may not appear after executable statement in block                         
spiffs-master/src/spiffs_cache.c", line 69: remark #270-D: declaration may not appear after executable statement in block                         
spiffs-master/src/spiffs_cache.c", line 70: remark #270-D: declaration may not appear after executable statement in block                         
spiffs-master/src/spiffs_cache.c", line 71: remark #270-D: declaration may not appear after executable statement in block                         
spiffs-master/src/spiffs_cache.c", line 95: remark #270-D: declaration may not appear after executable statement in block                         
spiffs-master/src/spiffs_cache.c", line 128: remark #270-D: declaration may not appear after executable statement in block                        
spiffs-master/src/spiffs_cache.c", line 129: remark #270-D: declaration may not appear after executable statement in block                        
spiffs-master/src/spiffs_cache.c", line 130: remark #270-D: declaration may not appear after executable statement in block                        
spiffs-master/src/spiffs_cache.c", line 151: remark #270-D: declaration may not appear after executable statement in block                        
spiffs-master/src/spiffs_cache.c", line 159: remark #270-D: declaration may not appear after executable statement in block                        
spiffs-master/src/spiffs_cache.c", line 173: remark #270-D: declaration may not appear after executable statement in block                        
spiffs-master/src/spiffs_cache.c", line 174: remark #270-D: declaration may not appear after executable statement in block                        
spiffs-master/src/spiffs_cache.c", line 175: remark #270-D: declaration may not appear after executable statement in block                        
spiffs-master/src/spiffs_cache.c", line 188: remark #270-D: declaration may not appear after executable statement in block                        
spiffs-master/src/spiffs_cache.c", line 216: remark #270-D: declaration may not appear after executable statement in block                        
spiffs-master/src/spiffs_cache.c", line 235: remark #270-D: declaration may not appear after executable statement in block                        
spiffs-master/src/spiffs_cache.c", line 250: remark #270-D: declaration may not appear after executable statement in block                        
spiffs-master/src/spiffs_cache.c", line 251: remark #270-D: declaration may not appear after executable statement in block                        
spiffs-master/src/spiffs_cache.c", line 268: remark #270-D: declaration may not appear after executable statement in block                        
spiffs-master/src/spiffs_cache.c", line 269: remark #270-D: declaration may not appear after executable statement in block                        
spiffs-master/src/spiffs_cache.c", line 270: remark #270-D: declaration may not appear after executable statement in block                        
spiffs-master/src/spiffs_cache.c", line 271: remark #270-D: declaration may not appear after executable statement in block                        
spiffs-master/src/spiffs_cache.c", line 280: remark #270-D: declaration may not appear after executable statement in block                        
spiffs-master/src/spiffs_cache.c", line 289: remark #270-D: declaration may not appear after executable statement in block                        
spiffs-master/src/spiffs_check.c", line 62: remark #270-D: declaration may not appear after executable statement in block                         
spiffs-master/src/spiffs_check.c", line 104: remark #270-D: declaration may not appear after executable statement in block                        
spiffs-master/src/spiffs_check.c", line 117: remark #270-D: declaration may not appear after executable statement in block                        
spiffs-master/src/spiffs_check.c", line 164: remark #270-D: declaration may not appear after executable statement in block                        
spiffs-master/src/spiffs_check.c", line 177: remark #270-D: declaration may not appear after executable statement in block                        
spiffs-master/src/spiffs_check.c", line 178: remark #270-D: declaration may not appear after executable statement in block                        
spiffs-master/src/spiffs_check.c", line 179: remark #270-D: declaration may not appear after executable statement in block                        
spiffs-master/src/spiffs_check.c", line 180: remark #270-D: declaration may not appear after executable statement in block                        
spiffs-master/src/spiffs_check.c", line 314: remark #270-D: declaration may not appear after executable statement in block                        
spiffs-master/src/spiffs_check.c", line 317: remark #270-D: declaration may not appear after executable statement in block                        
spiffs-master/src/spiffs_check.c", line 348: remark #270-D: declaration may not appear after executable statement in block                        
spiffs-master/src/spiffs_check.c", line 373: remark #270-D: declaration may not appear after executable statement in block                        
spiffs-master/src/spiffs_check.c", line 374: remark #270-D: declaration may not appear after executable statement in block                        
spiffs-master/src/spiffs_check.c", line 389: remark #270-D: declaration may not appear after executable statement in block                        
spiffs-master/src/spiffs_check.c", line 390: remark #270-D: declaration may not appear after executable statement in block                        
spiffs-master/src/spiffs_check.c", line 426: remark #270-D: declaration may not appear after executable statement in block                        
spiffs-master/src/spiffs_check.c", line 449: remark #270-D: declaration may not appear after executable statement in block                        
spiffs-master/src/spiffs_check.c", line 450: remark #270-D: declaration may not appear after executable statement in block                        
spiffs-master/src/spiffs_check.c", line 451: remark #270-D: declaration may not appear after executable statement in block                        
spiffs-master/src/spiffs_check.c", line 461: remark #270-D: declaration may not appear after executable statement in block                        
spiffs-master/src/spiffs_check.c", line 477: remark #270-D: declaration may not appear after executable statement in block                        
spiffs-master/src/spiffs_check.c", line 522: remark #270-D: declaration may not appear after executable statement in block                        
spiffs-master/src/spiffs_check.c", line 530: remark #270-D: declaration may not appear after executable statement in block                        
spiffs-master/src/spiffs_check.c", line 542: remark #270-D: declaration may not appear after executable statement in block                        
spiffs-master/src/spiffs_check.c", line 543: remark #270-D: declaration may not appear after executable statement in block                        
spiffs-master/src/spiffs_check.c", line 544: remark #270-D: declaration may not appear after executable statement in block                        
spiffs-master/src/spiffs_check.c", line 565: remark #270-D: declaration may not appear after executable statement in block                        
spiffs-master/src/spiffs_check.c", line 566: remark #270-D: declaration may not appear after executable statement in block                        
spiffs-master/src/spiffs_check.c", line 568: remark #270-D: declaration may not appear after executable statement in block                        
spiffs-master/src/spiffs_check.c", line 569: remark #270-D: declaration may not appear after executable statement in block                        
spiffs-master/src/spiffs_check.c", line 570: remark #270-D: declaration may not appear after executable statement in block                        
spiffs-master/src/spiffs_check.c", line 595: remark #270-D: declaration may not appear after executable statement in block                        
spiffs-master/src/spiffs_check.c", line 647: remark #270-D: declaration may not appear after executable statement in block                        
spiffs-master/src/spiffs_check.c", line 730: remark #270-D: declaration may not appear after executable statement in block                        
spiffs-master/src/spiffs_check.c", line 731: remark #270-D: declaration may not appear after executable statement in block                        
spiffs-master/src/spiffs_check.c", line 733: remark #270-D: declaration may not appear after executable statement in block                        
spiffs-master/src/spiffs_check.c", line 853: remark #270-D: declaration may not appear after executable statement in block                        
spiffs-master/src/spiffs_check.c", line 881: remark #270-D: declaration may not appear after executable statement in block                        
spiffs-master/src/spiffs_check.c", line 882: remark #270-D: declaration may not appear after executable statement in block                        
spiffs-master/src/spiffs_check.c", line 883: remark #270-D: declaration may not appear after executable statement in block                        
spiffs-master/src/spiffs_check.c", line 884: remark #270-D: declaration may not appear after executable statement in block                        
spiffs-master/src/spiffs_check.c", line 981: remark #270-D: declaration may not appear after executable statement in block                        
spiffs-master/src/spiffs_gc.c", line 46: remark #270-D: declaration may not appear after executable statement in block                            
spiffs-master/src/spiffs_gc.c", line 123: remark #270-D: declaration may not appear after executable statement in block                           
spiffs-master/src/spiffs_gc.c", line 139: remark #270-D: declaration may not appear after executable statement in block                           
spiffs-master/src/spiffs_gc.c", line 140: remark #270-D: declaration may not appear after executable statement in block                           
spiffs-master/src/spiffs_gc.c", line 141: remark #270-D: declaration may not appear after executable statement in block                           
spiffs-master/src/spiffs_gc.c", line 142: remark #270-D: declaration may not appear after executable statement in block                           
spiffs-master/src/spiffs_gc.c", line 254: remark #270-D: declaration may not appear after executable statement in block                           
spiffs-master/src/spiffs_gc.c", line 255: remark #270-D: declaration may not appear after executable statement in block                           
spiffs-master/src/spiffs_gc.c", line 258: warning #1944-D: unrecognized GCC pragma                                                                
spiffs-master/src/spiffs_gc.c", line 259: warning #1944-D: unrecognized GCC pragma                                                                
spiffs-master/src/spiffs_gc.c", line 261: warning #1944-D: unrecognized GCC pragma                                                                
spiffs-master/src/spiffs_gc.c", line 265: remark #270-D: declaration may not appear after executable statement in block                           
spiffs-master/src/spiffs_gc.c", line 308: remark #270-D: declaration may not appear after executable statement in block                           
spiffs-master/src/spiffs_gc.c", line 315: remark #270-D: declaration may not appear after executable statement in block                           
spiffs-master/src/spiffs_gc.c", line 319: remark #270-D: declaration may not appear after executable statement in block                           
spiffs-master/src/spiffs_gc.c", line 406: remark #270-D: declaration may not appear after executable statement in block                           
spiffs-master/src/spiffs_gc.c", line 407: remark #270-D: declaration may not appear after executable statement in block                           
spiffs-master/src/spiffs_hydrogen.c", line 49: remark #270-D: declaration may not appear after executable statement in block                      
spiffs-master/src/spiffs_hydrogen.c", line 52: remark #270-D: declaration may not appear after executable statement in block                      
spiffs-master/src/spiffs_hydrogen.c", line 93: remark #270-D: declaration may not appear after executable statement in block                      
spiffs-master/src/spiffs_hydrogen.c", line 96: remark #270-D: declaration may not appear after executable statement in block                      
spiffs-master/src/spiffs_hydrogen.c", line 94: warning #1944-D: unrecognized GCC pragma                                                           
spiffs-master/src/spiffs_hydrogen.c", line 95: warning #1944-D: unrecognized GCC pragma                                                           
spiffs-master/src/spiffs_hydrogen.c", line 96: warning #770-D: conversion from pointer to smaller integer                                         
spiffs-master/src/spiffs_hydrogen.c", line 97: warning #1944-D: unrecognized GCC pragma                                                           
spiffs-master/src/spiffs_hydrogen.c", line 106: warning #1944-D: unrecognized GCC pragma                                                          
spiffs-master/src/spiffs_hydrogen.c", line 107: warning #1944-D: unrecognized GCC pragma                                                          
spiffs-master/src/spiffs_hydrogen.c", line 108: warning #770-D: conversion from pointer to smaller integer                                        
spiffs-master/src/spiffs_hydrogen.c", line 109: warning #1944-D: unrecognized GCC pragma                                                          
spiffs-master/src/spiffs_hydrogen.c", line 126: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_hydrogen.c", line 159: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_hydrogen.c", line 160: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_hydrogen.c", line 192: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_hydrogen.c", line 193: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_hydrogen.c", line 210: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_hydrogen.c", line 211: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_hydrogen.c", line 218: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_hydrogen.c", line 286: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_hydrogen.c", line 288: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_hydrogen.c", line 318: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_hydrogen.c", line 320: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_hydrogen.c", line 364: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_hydrogen.c", line 365: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_hydrogen.c", line 416: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_hydrogen.c", line 417: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_hydrogen.c", line 423: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_hydrogen.c", line 446: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_hydrogen.c", line 447: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_hydrogen.c", line 448: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_hydrogen.c", line 524: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_hydrogen.c", line 525: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_hydrogen.c", line 571: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_hydrogen.c", line 572: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_hydrogen.c", line 595: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_hydrogen.c", line 596: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_hydrogen.c", line 621: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_hydrogen.c", line 622: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_hydrogen.c", line 623: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_hydrogen.c", line 660: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_hydrogen.c", line 661: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_hydrogen.c", line 687: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_hydrogen.c", line 688: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_hydrogen.c", line 689: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_hydrogen.c", line 693: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_hydrogen.c", line 713: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_hydrogen.c", line 714: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_hydrogen.c", line 731: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_hydrogen.c", line 732: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_hydrogen.c", line 755: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_hydrogen.c", line 758: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_hydrogen.c", line 789: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_hydrogen.c", line 805: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_hydrogen.c", line 830: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_hydrogen.c", line 831: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_hydrogen.c", line 833: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_hydrogen.c", line 893: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_hydrogen.c", line 894: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_hydrogen.c", line 900: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_hydrogen.c", line 927: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_hydrogen.c", line 928: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_hydrogen.c", line 929: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_hydrogen.c", line 930: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_hydrogen.c", line 988: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_hydrogen.c", line 989: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_hydrogen.c", line 990: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_hydrogen.c", line 991: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_hydrogen.c", line 992: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_hydrogen.c", line 1051: remark #270-D: declaration may not appear after executable statement in block                    
spiffs-master/src/spiffs_hydrogen.c", line 1074: remark #270-D: declaration may not appear after executable statement in block                    
spiffs-master/src/spiffs_hydrogen.c", line 1103: remark #270-D: declaration may not appear after executable statement in block                    
spiffs-master/src/spiffs_hydrogen.c", line 1104: remark #270-D: declaration may not appear after executable statement in block                    
spiffs-master/src/spiffs_hydrogen.c", line 1105: remark #270-D: declaration may not appear after executable statement in block                    
spiffs-master/src/spiffs_hydrogen.c", line 1142: remark #270-D: declaration may not appear after executable statement in block                    
spiffs-master/src/spiffs_hydrogen.c", line 1163: remark #270-D: declaration may not appear after executable statement in block                    
spiffs-master/src/spiffs_nucleus.c", line 19: remark #270-D: declaration may not appear after executable statement in block                       
spiffs-master/src/spiffs_nucleus.c", line 48: remark #270-D: declaration may not appear after executable statement in block                       
spiffs-master/src/spiffs_nucleus.c", line 90: remark #270-D: declaration may not appear after executable statement in block                       
spiffs-master/src/spiffs_nucleus.c", line 91: remark #270-D: declaration may not appear after executable statement in block                       
spiffs-master/src/spiffs_nucleus.c", line 251: remark #270-D: declaration may not appear after executable statement in block                      
spiffs-master/src/spiffs_nucleus.c", line 360: remark #270-D: declaration may not appear after executable statement in block                      
spiffs-master/src/spiffs_nucleus.c", line 361: remark #270-D: declaration may not appear after executable statement in block                      
spiffs-master/src/spiffs_nucleus.c", line 362: remark #270-D: declaration may not appear after executable statement in block                      
spiffs-master/src/spiffs_nucleus.c", line 382: remark #270-D: declaration may not appear after executable statement in block                      
spiffs-master/src/spiffs_nucleus.c", line 737: remark #270-D: declaration may not appear after executable statement in block                      
spiffs-master/src/spiffs_nucleus.c", line 880: remark #270-D: declaration may not appear after executable statement in block                      
spiffs-master/src/spiffs_nucleus.c", line 881: remark #270-D: declaration may not appear after executable statement in block                      
spiffs-master/src/spiffs_nucleus.c", line 882: remark #270-D: declaration may not appear after executable statement in block                      
spiffs-master/src/spiffs_nucleus.c", line 951: remark #270-D: declaration may not appear after executable statement in block                      
spiffs-master/src/spiffs_nucleus.c", line 952: remark #270-D: declaration may not appear after executable statement in block                      
spiffs-master/src/spiffs_nucleus.c", line 953: remark #270-D: declaration may not appear after executable statement in block                      
spiffs-master/src/spiffs_nucleus.c", line 959: remark #270-D: declaration may not appear after executable statement in block                      
spiffs-master/src/spiffs_nucleus.c", line 960: remark #270-D: declaration may not appear after executable statement in block                      
spiffs-master/src/spiffs_nucleus.c", line 1002: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_nucleus.c", line 1003: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_nucleus.c", line 1004: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_nucleus.c", line 1006: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_nucleus.c", line 1007: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_nucleus.c", line 1008: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_nucleus.c", line 1009: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_nucleus.c", line 1011: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_nucleus.c", line 1012: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_nucleus.c", line 1013: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_nucleus.c", line 1116: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_nucleus.c", line 1173: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_nucleus.c", line 1235: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_nucleus.c", line 1236: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_nucleus.c", line 1237: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_nucleus.c", line 1239: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_nucleus.c", line 1240: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_nucleus.c", line 1241: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_nucleus.c", line 1242: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_nucleus.c", line 1244: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_nucleus.c", line 1245: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_nucleus.c", line 1246: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_nucleus.c", line 1312: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_nucleus.c", line 1313: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_nucleus.c", line 1398: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_nucleus.c", line 1435: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_nucleus.c", line 1436: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_nucleus.c", line 1437: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_nucleus.c", line 1509: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_nucleus.c", line 1510: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_nucleus.c", line 1511: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_nucleus.c", line 1512: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_nucleus.c", line 1513: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_nucleus.c", line 1514: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_nucleus.c", line 1515: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_nucleus.c", line 1516: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_nucleus.c", line 1517: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_nucleus.c", line 1769: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_nucleus.c", line 1830: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_nucleus.c", line 1831: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_nucleus.c", line 1986: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_nucleus.c", line 1987: remark #270-D: declaration may not appear after executable statement in block                     
spiffs-master/src/spiffs_nucleus.c", line 1999: remark #270-D: declaration may not appear after executable statement in block                     

Thanks                                                                                                                                                  
James Lockwood

**Comment by pellepl** [comment]
Hi James,

regarding return codes, spiffs tries to be posix compliant. Though the errnos themselves are not. In any case, I do agree with you. Returning ```-x``` instead of ```-1``` where ```-x``` is the proper error code should not make a big difference as I've never seen anything else then ```if (SPIFFS_something(..) < 0) error```, and it allows for some smaller code. I personally find checking errno something of a nuisance - I'll look into it.

As for the huge list of warnings, I must admit I'm not jumping of joy of fixing all that ;). I guess this is not gcc or clang? Most of them seem to be ```declaration may not appear after executable statement in block```. But declaring variables anywhere in scope is C99 standard, and should be ok on most modern compilers. Yes, it may be regarded as sloppy coding, but if so then I am a sloppy coder. I would not dare to think of what would happen if I passed the spiffs code to Lint...

And of course I understand, having your compiler puking at you this way each time you build cannot be fun. Isn't there any way to disable those warnings? I could probable fix the non 270-D:s though.

**Comment by Nails-** [comment]
Peter,

Thanks for such a quick response. The compiler is from TI, for a Tiva chip (Arm M4F).

Just the non-270-D's would be the most helpful.  Once the library is built it doesn't have to do it anymore, but any other code that needs to import the .h header file to use spiffs would have thrown the nag warnings.

Thanks!

I'd clean up all the others if you want me to.

**Comment by pellepl** [comment]
Sorry for taking such time, busy here. See #83. now at least the headers should not puke at you.

**Comment by pellepl** [comment]
And for the return codes: #84

**Comment by pellepl** [comment]
> I'd clean up all the others if you want me to.

Thanks, but I actually prefer having it as is. It is sort of part of what I think makes the code look pretty. But thanks for the offer!
