### ISSUE TITLE
SPIFFS_vis / SPIFFS_info mutex lock-wait hang

### ISSUE THREAD

**Issue by dpruessner** [pellepl/spiffs#87]
Hi Peter,
When I `#define SPIFFS_LOCK(fs)` with a MUTEX locking system that does not allow recursive locks, `SPIFFS_vis` hangs from the call to `SPIFFS_info` at the end (**spiffs_hydrogen.c:1175**).

I think that moving the `SPIFFS_UNLOCK(fs)` above the `SPIFFS_info` call is still safe.

-- Daniel

**Comment by pellepl** [comment]
Hi Daniel,

Yes you're right. Thanks for reporting! 

Cheers/ P
