### ISSUE TITLE
In some cases in SPIFFS_write, SPIFFS_lseek and SPIFFS_vis SPIFFS_API_CHECK_RES is called in stead of SPIFFS_API_CHECK_RES_UNLOCK

### ISSUE THREAD

**Issue by JackJefferson** [pellepl/spiffs#88]
SPIFFS_API_CHECK_RES checks the result and returns from the function. When a lock was done earlier in the function, this lock remains and is never unlocked.
Call SPIFFS_API_CHECK_RES_UNLOCK in stead in the following 3 functions:
SPIFFS_write, SPIFFS_lseek and SPIFFS_vis

**Comment by pellepl** [comment]
Thanks! Will look into it.

Cheers / P

2016-05-04 10:58 GMT+02:00 JackJefferson <notifications@github.com>:
