### ISSUE TITLE
`SPIFFS_PH_FLAG_FINAL` flag not set when marking a page as deleted

### ISSUE THREAD

**Issue by arjun789** [pellepl/spiffs#91]
Shouldn't the `SPIFFS_PH_FLAG_FINAL` flag be set [here](https://github.com/pellepl/spiffs/blob/master/src/spiffs_nucleus.c#L735)

**Comment by pellepl** [comment]
You're a bold person walking down the internals of spiffs I must say :)

In this case, no - the delete flag has precedence over the final flag. It
is valid to delete pages that have no been finalized.

Now while writing I get a bit uncertain, so I'll leave this open until I
can check it more thoroughly.

Thanks for the headsup!

2016-05-20 13:06 GMT+02:00 Arjun <notifications@github.com>:

**Comment by pellepl** [comment]
It's ok. Deleted pages may be unfinalized. The finalization is when spiffs is done writing or moving a page.
