### ISSUE TITLE
NullPointer dereferencing

### ISSUE THREAD

**Issue by niclash** [pellepl/spiffs#92]
https://github.com/pellepl/spiffs/blob/master/src/spiffs_cache.c#L154

A few lines earlier there is a if(cp), which means that cp can be returned "0" from the previous function, yet the cp->ix is called on line 154, which I think (not 100% sure yet) cases segfault on my system sometimes.

**Comment by pellepl** [comment]
Um yes, that particular piece of code was pretty ugly, sorry for that. I will clean it uo. 

Purely functionally, before the page allocation there is a call to spiffs_cache_page_remove_oldest - this ensures that a page always is available. So cp should never be null.

**Comment by niclash** [comment]
Possibly... So, I think you suggest that my code is suffering from
concurrency problems, which is totally possible.

On Sat, May 28, 2016 at 3:28 PM, Peter Andersson <notifications@github.com>
wrote:

> Um yes, that particular piece of code was pretty ugly, sorry for that. I
> will clean it uo.
>
> Purely functionally, before the page allocation there is a call to
> spiffs_cache_page_remove_oldest - this ensures that a page always is
> available. So cp should never be null.
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/pellepl/spiffs/issues/92#issuecomment-222295068>, or mute
> the thread
> <https://github.com/notifications/unsubscribe/AAGgxaVn2A8HEf4AxmI3X_nCICXDmNwwks5qF-6xgaJpZM4IpAdl>
> .
>



-- 
Niclas Hedhman, Software Developer
http://zest.apache.org - New Energy for Java

**Comment by pellepl** [comment]
Might be. I've cleaned things up a bit, you could try this change also. Though I'd bet all butter in Smalland that it won't do anything.

Cheers for notifying me!
